ieducar_1604:
  build: .
  environment:
    - CORE_EXT_CONFIGURATION_ENV=development
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/html/i-educar/
  links:
    - postgres95
  container_name: ieducar_1604

postgres95:
  volumes:
    - /var/lib/postgresql/data
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - "5430:5432"
